### PR TITLE
fix: X-axis labels and ticks

### LINKED ISSUE #4408: X-axis not showing dates when filtering viewer graph by days/months
For reference [here](https://github.com/owncast/owncast/blob/develop/web/components/admin/Chart.tsx) is the source behind most of our admin charts.

### Discussed in https://github.com/owncast/owncast/discussions/4402

<div type='discussions-op-text'>

<sup>Originally posted by **fsan2val** June 26, 2025</sup>
Hello Owncast team,

I'd like to suggest a UX improvement in the viewer graph. When selecting time ranges like 12 or 24 hours, the X-axis shows hours correctly, making the graph easy to interpret.

However, when switching to longer ranges like 7 days, 30 days, or 3–6 months, the X-axis still only shows hourly timestamps, which makes it almost impossible to know which day or month each point refers to.

**Suggestion:**

For 7 or 30-day ranges: Show days or specific date labels (e.g. "Jun 20", "Jun 21", etc.).

For 3–6 month ranges: Show month labels (e.g. "Mar", "Apr", "May").

This would greatly enhance the readability of the graph when analyzing viewership trends over time.

Thank you for your time and for building such a great open-source project!

estadisticas fecha
</div>

### PR DESCRIPTION
**Pull request by amisha-adwani**
## Double check

- [X] I included a screenshot, logs, or example payload to demonstrate the change.
- [X] This is a frontend change and it supports [translations](https://docs.owncast.dev/web-translations), or it's not a frontend change.
- [X] This change has actually been tested.
- [X] The code has been run through the proper linters and/or formatters for the language.
- [X] There is an issue discussing this change and it's assigned to me.
- [X] I read the "Read first" details about filing this PR.

---
## Description

This PR fixes the X-axis label formatting for chart time windows. Previously, charts were showing only hourly timestamps making it hard to interpret which day or month each point referred to

- Short time windows (12h, 24h) now display as `H:mm`
- Medium windows (7d,20d) display as `MMM d`
- Long windows (3mo,6mo) display as `MMM`

Also set `maxTicksLimit` to 10 to prevent crowding.

Fixes #4408 

### Changes in code 

- Added a new optional prop `timeWindowKey` to ChartProps.
- Created a new helper function `getLabelFormat` to return different date label formats based on timeWindowKey.
- Updated createGraphDataset to accept a `labelFormat` parameter instead of using a hardcoded `H:mma`.
- Modified chart data creation to pass labelFormat into createGraphDataset.
- In `viewer-info.tsx`, added state for timeWindowKey, updated onTimeWindowSelect to set it, and passed it as a prop to the Chart component.

## Screenshot Examples or Logs

image
image
image

---

### CODE REVIEW

File: web/components/admin/Chart.tsx [hunk 1]
```diff
@@ -45,13 +45,22 @@ export type ChartProps = {
...
+  timeWindowKey?: number; 
 };
 
-function createGraphDataset(dataArray) {
+function getLabelFormat(timeWindowKey?: number) {
+  // 0: current stream, 1: 12h, 2: 24h, 3: 7d, 4: 30d, 5: 3mo, 6: 6mo
+  if (timeWindowKey === 1 || timeWindowKey === 2) return 'H:mm'; // 12/24h: hour
+  if (timeWindowKey === 3 || timeWindowKey === 4) return 'MMM d'; // 7/30d: day
+  if (timeWindowKey === 5 || timeWindowKey === 6) return 'MMM'; // 3/6mo: month
+  return 'H:mm';
```
Comment (gabek) [inline web/components/admin/Chart.tsx]: Instead of using a plain int to represent a time window, how would you feel about using a typescript enum instead? Then you could literally say it's a `TimeWindow.Day` or whatever.

Comment (amisha-adwani) [reply web/components/admin/Chart.tsx]: alright, ive updated the code to use enum. please review

Comment (amisha-adwani) [reply web/components/admin/Chart.tsx]: why is browser test failing and how can i fix it?

Comment (gabek) [reply web/components/admin/Chart.tsx]: Make sure you're running Prettier against your changes.

**Comment by gabek** [comment]
This works great! Thanks so much for working on it and being receptive to the feedback!
