### PR TITLE
fix(web): set page title on chat embed pages

### LINKED ISSUE #4794: Firefox under Arch Linux fails to display title for popped-out chat.
Currently popping out chat when viewing the stream in Firefox on Arch results in the chat window title not being set. I tested in Chromium and confirmed that it appears to appropriately display the title there. I don't know if this is fixable or if it's a Firefox quirk that isn't easily worked around, but I'm hoping it would be pretty trivial. I'm not super well versed in Next.js so I got a bit turned around on what was being set where in the project when I took a look.

Also, really not a big deal, but the title in Chromium is not the most human-friendly (`[site-name]/embed/chat/readwrite`), not sure if the distinction between readwrite and readonly in the title needs to be kept but updating that to be more natural language would be nice as well.

### PR DESCRIPTION
**Pull request by costajohnt**
## Required checklist

**Do not remove this section.** These checkboxes are required and validated.

- [x] I have personally tested these changes and verified they work as intended.
- [x] I understand the code I'm submitting and can explain how it works if asked.
- [x] I included a screenshot, logs, example payload to demonstrate the change, or it really doesn't need it.
- [x] This is a frontend change and it supports [translations](https://docs.owncast.dev/web-translations), or it's not a frontend change.
- [x] The code has been run through the proper linters and/or formatters for the language.
- [x] There is an issue discussing this change and it's assigned to me.

---

## Summary

Fixes #4794

The chat embed pages (`/embed/chat/readwrite` and `/embed/chat/readonly`) had no `<title>` tag, which caused:
- **Firefox**: Popup chat windows displayed a blank title bar, making window management difficult
- **Chromium**: Showed the raw URL path (e.g., `[host]/embed/chat/readwrite`) instead of a meaningful name

This PR adds a `<Head><title>` tag to both chat embed pages using the server's configured stream name, following the same pattern used in `OfflineEmbed.tsx`. The title format is `{streamName} Chat`.

## Changes

- **`web/pages/embed/chat/readwrite/index.tsx`**: Added `Head` import and `<title>` tag using the existing `name` from `clientConfig`
- **`web/pages/embed/chat/readonly/index.tsx`**: Added `Head` import, `clientConfigStateAtom` + `ClientConfig` imports, and `<title>` tag

## Test plan

- [x] ESLint passes on both changed files
- [x] Open a stream page → pop out chat → verify the popup window title shows `{streamName} Chat` in both Firefox and Chromium
- [x] Navigate to `/embed/chat/readonly` directly → verify the page title is set

## Screenshots
Screenshot 2026-03-06 at 8 50 21 AM
Screenshot 2026-03-06 at 8 43 31 AM

### CODE REVIEW

File: web/pages/embed/chat/readonly/index.tsx [hunk 1]
```diff
@@ -1,27 +1,41 @@
...
 export default function ReadOnlyChatEmbed() {
   const currentUser = useRecoilValue(currentUserAtom);
   const messages = useRecoilValue<ChatMessage[]>(visibleChatMessagesSelector);
+  const clientConfig = useRecoilValue<ClientConfig>(clientConfigStateAtom);
   const isChatAvailable = useRecoilValue(isChatAvailableSelector);
 
+  const { name } = clientConfig;
+
+  useEffect(() => {
+    document.title = name ? `${name} Chat` : 'Chat';
```
Comment (gabek) [inline web/pages/embed/chat/readonly/index.tsx]: If we're going to append `chat` at the end of it (in English), we'll need to translate the entire string.

File: docs/api/index.html
Comment (gabek) [inline docs/api/index.html:1]: API docs shouldn't need to be changed.

**Comment by gabek** [comment]
This PR still has 28 files changed and can't move forward until that's resolved.
